version: '3.3'

services:
  eaipannotator_server:
    labels:
      - traefik.http.routers.eaipannotator.entrypoints=websecure
      - traefik.http.routers.eaipannotator.tls=true
      # - traefik.http.routers.eaipannotator.tls.certresolver=lets-encrypt

  eaipannotator_ui:
    labels:
      - traefik.http.routers.eaipannotator-ui.entrypoints=websecure
      - traefik.http.routers.eaipannotator-ui.tls=true
      # - traefik.http.routers.eaipannotator-ui.tls.certresolver=lets-encrypt

  traefik:
    image: traefik:v2.4
    container_name: traefik
    command:
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=eaipannotator"
      - '--providers.file.directory=/etc/traefik/rules'
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.websecure.address=:443"
      - "--providers.file.directory=/etc/traefik/dynamic_conf"
      - "--providers.file.watch=true"
      # - "--certificatesResolvers.lets-encrypt.acme.email=${ACME_EMAIL:?Please set the ACME_EMAIL env variable}"
      # - "--certificatesResolvers.lets-encrypt.acme.tlsChallenge=true"
      # - "--certificatesResolvers.lets-encrypt.acme.storage=/letsencrypt/acme.json"
      # Uncomment to get Traefik dashboard
      # - "--entryPoints.dashboard.address=:8090"
      # - "--api.dashboard=true"
    ports:
      - 80:80
      - 443:443
    volumes:
      # - eaipannotator_letsencrypt:/letsencrypt
      - eaipannotator_certs:/certs/:ro
      - ./traefik.yml:/etc/traefik/dynamic_conf/traefik.yml:ro

volumes:
  # eaipannotator_letsencrypt:
  eaipannotator_certs:
    driver_opts:
      type: none
      device: /home/sr/Anick/outdu-cvat/cvat_jnj_new/cvat/ssl
      o: bind
